# Generated by Django 3.2.10 on 2022-03-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_image_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
