# Generated by Django 3.2.10 on 2022-03-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
