# Generated by Django 3.2.10 on 2022-03-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_departments_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
