# Generated by Django 3.2.10 on 2022-03-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0009_auto_20220320_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste_postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
