# Generated by Django 3.2.10 on 2022-03-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_teste_postagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teste_postagem',
            new_name='Post',
        ),
    ]
