# Generated by Django 3.2.10 on 2022-04-01 00:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_programacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('genero', models.CharField(choices=[('acao', 'Ação'), ('animacao', 'Animação'), ('aventura', 'Aventura'), ('comedia', 'Comédia'), ('drama', 'Drama'), ('suspense', 'Suspense'), ('terror', 'Terror')], max_length=30)),
                ('diretor', models.CharField(max_length=100)),
                ('class_indic', models.CharField(choices=[('l', 'Livre'), ('10', '+10'), ('12', '+12'), ('14', '+14'), ('16', '+16'), ('18', '+18')], default='l', max_length=10)),
                ('duracao', models.IntegerField(default=100)),
                ('data_estreia', models.DateField(default=datetime.date.today)),
                ('em_cartaz', models.BooleanField(default=True)),
                ('poster', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=2)),
                ('capacidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('2d', '2D'), ('3d', '3D'), ('premium2d', '2D - Premium'), ('premium3d', '3D - Premium')], default='2d', max_length=40)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario', models.CharField(choices=[('13h30', '13:30'), ('16h30', '16:30'), ('19h30', '19:30'), ('22h30', '22:30')], max_length=5)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.filme')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.salas')),
            ],
        ),
        migrations.AddField(
            model_name='salas',
            name='sessoes',
            field=models.ManyToManyField(through='cinema.Sessao', to='cinema.Filme'),
        ),
        migrations.AddConstraint(
            model_name='sessao',
            constraint=models.UniqueConstraint(fields=('sala', 'data', 'horario'), name='Unicos'),
        ),
        migrations.AddConstraint(
            model_name='salas',
            constraint=models.UniqueConstraint(fields=('nome', 'cinema'), name='Unico'),
        ),
    ]
