# Generated by Django 3.2.10 on 2022-04-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_auto_20220331_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='horario',
            field=models.CharField(max_length=5),
        ),
    ]
