# Generated by Django 3.2.10 on 2022-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_sessao_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(default='Sinopse'),
        ),
    ]
