# Generated by Django 3.2.10 on 2022-04-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_filme_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='legenda',
            field=models.CharField(choices=[('dublado', 'Dublado'), ('legendado', 'Legendado')], default='dublado', max_length=10),
        ),
    ]
