# Generated by Django 3.2.6 on 2022-06-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_salas_legenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Add_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=40, verbose_name='Book Name')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.add_cat')),
            ],
        ),
    ]
